# Django Web
# Postgresql
# Nocodb

version: "3"

services:
  django:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    depends_on:
      - pgdb
  pgdb:
    image: postgres
    container_name: pgdb
    environment:
      - POSTGGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  Nocodb:
    image: nocodb
    container_name: nocodb
    environment:
      - NOCODB_DB=nocodb
      - NOCODB_USER='krongkan.nfols@gmail.com'
      - NOCODB_PASSWORD='Nocodb_Password181243'