# Generated by Django 3.2.5 on 2022-04-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_invoice_item_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='myimage'),
        ),
    ]
